# PyTortoiseGit - a Python reimplementation mirroring TortoiseGit.
# Copyright (C) 2026  PyTortoiseGit contributors
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# This program is derived from and mirrors the TortoiseGit project.
"""icon_map.py —— TortoiseGit 图标资源映射（ID -> 资源文件名）。"""

ICON_MAP = {
    "IDI_ABOUT": "menuabout.ico",
    "IDI_ACTIONADDED": "actionadded.ico",
    "IDI_ACTIONCONFLICTED": "actionconflicted.ico",
    "IDI_ACTIONDELETED": "actiondeleted.ico",
    "IDI_ACTIONERROR": "actionerror.ico",
    "IDI_ACTIONFETCHING": "actionfetching.ico",
    "IDI_ACTIONMODIFIED": "actionmodified.ico",
    "IDI_ACTIONREPLACED": "actionreplaced.ico",
    "IDI_ADD": "menuadd.ico",
    "IDI_ADDEDLINE": "lineadded.ico",
    "IDI_ADD_BKG": "AddBackground.ico",
    "IDI_APP": "Tortoise.ico",
    "IDI_APPSMALL": "TortoiseSmall.ico",
    "IDI_BISECT": "menubisect.ico",
    "IDI_BISECT_RESET": "menubisectreset.ico",
    "IDI_BLAME": "TortoiseGitBlame.ico",
    "IDI_BLAME_POPUP_BLAME": "TortoiseGitBlame.ico",
    "IDI_BLAME_POPUP_COMPARE": "menucompare.ico",
    "IDI_BLAME_POPUP_COPY": "copy.ico",
    "IDI_BLAME_POPUP_LOG": "menulog.ico",
    "IDI_BUGTRAQ": "bugtraq.ico",
    "IDI_CANCELNORMAL": "cancel-normal.ico",
    "IDI_CANCELPRESSED": "cancel-pressed.ico",
    "IDI_CERTCHECK": "certcheck.ico",
    "IDI_CFM_BKG": "CFMBackground.ico",
    "IDI_CHERRYPICK": "cherry-pick.ico",
    "IDI_CLEANUP": "menucleanup.ico",
    "IDI_CLIPPASTE": "clippaste.ico",
    "IDI_CLONE": "menucheckout.ico",
    "IDI_CODE": "code.ico",
    "IDI_COMBINE": "menucombine.ico",
    "IDI_COMMIT": "menucommit.ico",
    "IDI_COMMIT_BKG": "CommitBackground.ico",
    "IDI_CONFLICT": "menuconflict.ico",
    "IDI_CONFLICTEDIGNOREDLINE": "lineconflictedignored.ico",
    "IDI_CONFLICTEDLINE": "lineconflicted.ico",
    "IDI_COPY": "menucopy.ico",
    "IDI_COPYCLIP": "copy.ico",
    "IDI_CREATEPATCH": "menudiff.ico",
    "IDI_CREATEREPOS": "menucreaterepos.ico",
    "IDI_DAEMON": "menudaemon.ico",
    "IDI_DELETE": "menudelete.ico",
    "IDI_DIALOGS": "dialogs.ico",
    "IDI_DIFF": "menucompare.ico",
    "IDI_DRIVES": "Drives.ico",
    "IDI_EDIT": "menuedit.ico",
    "IDI_EQUALLINE": "lineequal.ico",
    "IDI_EXECUTABLEOVL": "executableovl.ico",
    "IDI_EXPLORER": "explorer.ico",
    "IDI_EXPORT": "menuexport.ico",
    "IDI_EXTERNALOVL": "externalovl.ico",
    "IDI_FILE": "file.ico",
    "IDI_FILTEREDIT": "filteredit.ico",
    "IDI_GENERAL": "general.ico",
    "IDI_GITCONFIG": "gitconfig.ico",
    "IDI_GITCREDENTIAL": "gitcredential.ico",
    "IDI_GITFOLDER": "gitfolder.ico",
    "IDI_GITREMOTE": "gitremote.ico",
    "IDI_GRAPHBAR": "graph-bar.ico",
    "IDI_GRAPHBARSTACKED": "graph-bar-stacked.ico",
    "IDI_GRAPHLINE": "graph-line.ico",
    "IDI_GRAPHLINESTACKED": "graph-line-stacked.ico",
    "IDI_GRAPHPIE": "graph-pie.ico",
    "IDI_HELP": "menuhelp.ico",
    "IDI_HOOK": "hook.ico",
    "IDI_ICONSET": "iconset.ico",
    "IDI_IGNORE": "menuignore.ico",
    "IDI_IMPORTPATHCES_BKG": "ImportPatchesBackground.ico",
    "IDI_INDETERMINATE": "indeterminate.ico",
    "IDI_JUMPDOWN": "jumpdown.ico",
    "IDI_JUMPUP": "jumpup.ico",
    "IDI_LFS": "menulfs.ico",
    "IDI_LFSLOCK": "menulock.ico",
    "IDI_LFSUNLOCK": "menuunlock.ico",
    "IDI_LIBRARY_WIN10": "library-win10.ico",
    "IDI_LINEEDITED": "lineedited.ico",
    "IDI_LINEENDINGCR": "LineEndingCR.ico",
    "IDI_LINEENDINGCRLF": "LineEndingCRLF.ico",
    "IDI_LINEENDINGLF": "LineEndingLF.ico",
    "IDI_LINEMARKED": "linemarked.ico",
    "IDI_LOCK_BKG": "LockBackground.ico",
    "IDI_LOG": "menulog.ico",
    "IDI_LOGFILTER": "logfilter.ico",
    "IDI_LOOKANDFEEL": "lookandfeel.ico",
    "IDI_MENUFILE": "tsvnmenufile.ico",
    "IDI_MENUFOLDER": "tsvnmenufolder.ico",
    "IDI_MENULINK": "tsvnmenulink.ico",
    "IDI_MENUMULTIPLE": "tsvnmenumultiple.ico",
    "IDI_MENUSENDMAIL": "menusendmail.ico",
    "IDI_MENUSYNC": "menusync.ico",
    "IDI_MERGE": "menumerge.ico",
    "IDI_MERGEABORT": "menumergeabort.ico",
    "IDI_MERGEACTIVE": "menumerge.ico",
    "IDI_MISC": "misc.ico",
    "IDI_MOVEDLINE": "moved.ico",
    "IDI_NOTEPAD": "notepad.ico",
    "IDI_OPEN": "open.ico",
    "IDI_OUTPUT_WND": "output_wnd.ico",
    "IDI_OUTPUT_WND_HC": "output_wnd_hc.ico",
    "IDI_PATCH": "menupatch.ico",
    "IDI_PICK": "menupick.ico",
    "IDI_PROPERTIES_WND": "properties_wnd.ico",
    "IDI_PROPERTIES_WND_HC": "properties_wnd_hc.ico",
    "IDI_PROXY": "proxy.ico",
    "IDI_PULL": "pull1.ico",
    "IDI_PUSH": "Push.ico",
    "IDI_REBASE": "menurebase.ico",
    "IDI_REFRESH": "refresh.ico",
    "IDI_RELOCATE": "menurelocate.ico",
    "IDI_REMOVEDLINE": "lineremoved.ico",
    "IDI_RENAME": "menurename.ico",
    "IDI_REPOBROWSE": "menurepobrowse.ico",
    "IDI_REPOBROWSER_BKG": "RepoBrowserBackground.ico",
    "IDI_RESET": "reset.ico",
    "IDI_RESOLVE": "menuresolve.ico",
    "IDI_RESOLVE_BKG": "ResolveBackground.ico",
    "IDI_RESTORE": "restore.ico",
    "IDI_RESTOREOVL": "restoreovl.ico",
    "IDI_REVERT": "menurevert.ico",
    "IDI_REVERT_BKG": "RevertBackground.ico",
    "IDI_REVISIONGRAPH": "menurevisiongraph.ico",
    "IDI_SAVE": "save.ico",
    "IDI_SAVEAS": "saveas.ico",
    "IDI_SAVEDDATA": "saveddata.ico",
    "IDI_SETTINGS": "menusettings.ico",
    "IDI_SET_OVERLAYS": "Overlays.ico",
    "IDI_SHELVE": "menushelve.ico",
    "IDI_SHOWBRANCHES": "showbranches.ico",
    "IDI_SHOWCHANGED": "menushowchanged.ico",
    "IDI_SKIP": "menuskip.ico",
    "IDI_SNIPPET": "snippet.ico",
    "IDI_SPELL": "spell.ico",
    "IDI_SQUASH": "menusquash.ico",
    "IDI_SWITCH": "menuswitch.ico",
    "IDI_SWITCHLEFTRIGHT": "switch.ico",
    "IDI_SWITCH_BKG": "SwitchBackground.ico",
    "IDI_SYMLINKOVL": "symlinkovl.ico",
    "IDI_TAG": "Tag.ico",
    "IDI_THUMB_DOWN": "thumb_down.ico",
    "IDI_THUMB_UP": "thumb_up.ico",
    "IDI_TORTOISEBLAME": "TortoiseGitBlame.ico",
    "IDI_TORTOISEUDIFF": "TortoiseUDiff.ico",
    "IDI_UNLOCK_BKG": "UnlockBackground.ico",
    "IDI_UNSHELVE": "menuunshelve.ico",
    "IDI_UPDATE": "menuupdate.ico",
    "IDI_UPDATE_BKG": "UpdateBackground.ico",
    "IDI_WHITESPACELINE": "linewhitespace.ico",
    "IDR_MAINFRAME": "Tortoise.ico",
    "IDR_TORTOISE_GIT_BLAME_MAINFRAME": "TortoiseGitBlame.ico",
}
