"""strings.py —— 镜像 TortoiseGit 的 ResText。

界面文案统一放在中文字符串表，通过 tr() 取用，便于后续替换为完整 i18n。
"""

# PyTortoiseGit - a Python reimplementation mirroring TortoiseGit.
# Copyright (C) 2026  PyTortoiseGit contributors
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# This program is derived from and mirrors the TortoiseGit project.

from __future__ import annotations

from typing import Callable, Dict, Optional

# 缓存自实现，若启用 Qt QTranslator 可替换 _current_gettext
_translator: Optional[Callable[[str], str]] = None

# 当前界面语言："zh"（中文，默认）或 "en"（英文）
_current_lang: str = "zh"

STRINGS: Dict[str, str] = {
    # ---- 通用 ----
    "app_name": "PyTortoiseGit",
    "ok": "确定",
    "cancel": "取消",
    "close": "关闭",
    "apply": "应用",
    "yes": "是",
    "no": "否",
    "browse": "浏览...",
    "loading": "加载中...",
    "error": "错误",
    "warning": "警告",
    "information": "提示",
    "progress": "进度",
    "progress_title": "Git 命令进度",
    "progress_wait": "请稍候…",
    "progress_success": "成功",
    "progress_unclean": "git 未能干净退出（退出码 {}）",
    "menu_pull": "Pull",
    "menu_fetch": "Fetch",
    "menu_push": "Push",
    "push_no_remote": "请选择远程或填写 URL",
    "abort": "中止",
    "refresh": "刷新",
    "settings": "设置",
    "repository": "仓库",
    "file": "文件",
    "folder": "文件夹",

    # ---- 关于对话框 (AboutDlg) ----
    "about_title": "关于",
    "about_text": "PyTortoiseGit 是基于 PySide6 用 Python 重写的 TortoiseGit 跨平台客户端。",
    "about_version": "版本",
    "about_website": "仓库",
    "about_git_version": "Git 版本",

    # ---- 命令行分发 ----
    "unknown_command": "未知命令：{command}",
    "missing_command": "请使用 /command:<name> 指定要执行的命令",
    "command_failed": "命令执行失败：{name} —— {message}",

    # ---- 仓库 ----
    "repo_not_found": "不是 git 仓库：{path}",
    "select_repo_folder": "选择存放 Git 仓库的文件夹",
    "open_repo": "打开仓库...",

    # ---- Stash (StashDlg / StashSave) ----
    "stash_title": "Stash",
    "stash_message_group": "Stash &Message",
    "stash_options_group": "Options",
    "stash_include_untracked": "include &untracked",
    "stash_all": "--&all",
    "stash_untracked_warning": "Including untracked files will also add untracked files to the stash. Are you sure you want to continue?",
    "stash_ref": "引用",
    "stash_subject": "说明",
    "stash_date": "时间",
    "stash_create": "创建暂存",
    "stash_apply": "应用",
    "stash_pop": "弹出并应用",
    "stash_drop": "丢弃",
    "stash_clear": "清空全部",
    "stash_msg": "暂存说明",
    "stash_untracked": "包含未跟踪文件",
    "stash_empty": "没有暂存的修改",
    "stash_confirm_clear": "确定清空全部暂存吗？",
    "stash_created": "已创建暂存",
    "stash_applied": "已应用暂存",
    "stash_popped": "已弹出暂存",
    "stash_dropped": "已丢弃暂存",

    # ---- 合并/变基与冲突 ----
    "merge_title": "合并",
    "merge_branch": "合并分支",
    "merge_noff": "不使用快进 (--no-ff)",
    "merge_squash": "压缩提交 (--squash)",
    "merge_nocommit": "不自动提交 (--no-commit)",
    "merge_message": "提交信息",
    "merge_perform": "开始合并",
    "merge_merged": "合并完成",
    "merge_conflicts": "存在冲突，请解决后在提交对话框中提交",
    "merge_in_progress": "仓库正处于合并状态",
    "merge_abort": "中止合并",
    "merge_aborted": "已中止合并",
    "merge_pick": "选择要合并的分支",
    "rebase_title": "变基 (Rebase)",
    "rebase_target": "目标分支",
    "rebase_interactive": "交互式 (-i)",
    "rebase_autostash": "自动暂存 (--autostash)",
    "rebase_start": "开始变基",
    "rebase_continue": "继续变基",
    "rebase_abort": "中止变基",
    "conflict_resolved": "已标记解决",
    "conflict_mark": "标记解决",
    "conflict_ours": "采用我方 (ours)",
    "conflict_theirs": "采用对方 (theirs)",
    "conflict_extmerge": "外部合并工具",
    "conflict_all": "全部标记解决",
    "conflicts_title": "合并冲突",
    "conflicts_none": "没有冲突",

    # ---- Submodule ----
    "submodule_title": "子模块",
    "submodule_path": "路径",
    "submodule_sha": "提交",
    "submodule_status": "状态",
    "submodule_desc": "远程/说明",
    "submodule_add": "添加子模块",
    "submodule_update": "更新",
    "submodule_update_recursive": "递归更新 (--recursive)",
    "submodule_update_init": "初始化后更新 (--init)",
    "submodule_sync": "同步",
    "submodule_deinit": "取消初始化",
    "submodule_url": "URL",
    "submodule_open_log": "打开日志",
    "submodule_empty": "没有子模块",
    "submodule_added": "已添加子模块",
    "submodule_updated": "子模块已更新",
    "submodule_deinited": "子模块已取消初始化",

    # ---- 外部工具 ----
    "xtool_diffcmd": "外部 diff 工具命令",
    "xtool_mergecmd": "外部 merge 工具命令",
    "xtool_diff_hint": "示例：\"d:\\bin\\bc.exe\" {left} {right}",
    "xtool_merge_hint": "示例：\"d:\\bin\\bc.exe\" {base} {ours} {theirs} {out}",
    "xtool_launch_diff": "外部工具比较",
    "xtool_launch_merge": "外部工具合并",
    "xtool_not_configured": "未配置外部工具，请在设置中填写命令模板",
    "xtool_diff": "外部差异工具 (tortoisegit.externaldiff)",
    "xtool_merge": "外部合并工具 (tortoisegit.externalmerge)",
    "rebase_aborted": "已中止变基",
    "status": "状态",
    "confirm": "确认",

    # ---- 设置 - General 页 ----
    "set_lang": "&语言：",
    "set_gitexe": "&Git.exe 路径：",
    "set_extrapath": "&额外 PATH：",
    "set_ver": "版本：",
    "set_browse": "选择 Git 目录",
    "set_env": "环境变量",
    "set_firststart": "First Start Wizard",
    "firststart_unavailable": "First Start Wizard 不可用。",
    "set_library": "Create Library",
    "set_library_done": "Python 版无需额外创建库。",
    "set_checknewer": "检查更新",
    "set_checknewer_msg": "当前版本：{ver}。此功能为占位，尚不支持自动联网检查。",

    # ---- TortoiseGitMerge 主窗口 ----
    "tm_title": "TortoiseGitMerge - {}",
    "tm_file": "文件(&F)",
    "tm_edit": "编辑(&E)",
    "tm_nav": "导航(&N)",
    "tm_view": "视图(&V)",
    "tm_help": "帮助(&H)",
    "tm_open": "打开",
    "tm_save": "保存",
    "tm_saveas": "另存为...",
    "tm_mark": "标记为已解决",
    "tm_patch": "创建补丁文件",
    "tm_reload": "重新加载",
    "tm_enable_edit": "允许编辑",
    "tm_exit": "退出",
    "tm_undo": "撤销",
    "tm_redo": "重做",
    "tm_copy": "复制",
    "tm_paste": "粘贴",
    "tm_use_left_block": "使用左侧块",
    "tm_use_left_file": "使用左侧文件",
    "tm_use_left_before": "先左后右",
    "tm_use_right_before": "先右后左",
    "tm_use_theirs": "使用左侧文本块",
    "tm_use_mine": "使用右侧文本块",
    "tm_use_theirs_then": "先左后右文本块",
    "tm_use_mine_then": "先右后左文本块",
    "tm_find": "查找",
    "tm_find_next": "查找下一个",
    "tm_find_prev": "查找上一个",
    "tm_goto": "跳转到行",
    "tm_regex": "配置正则过滤器",
    "tm_ignore_comments": "忽略注释",
    "tm_next_diff": "下一处差异",
    "tm_prev_diff": "上一处差异",
    "tm_next_conf": "下一处冲突",
    "tm_prev_conf": "上一处冲突",
    "tm_next_inline": "下一处行内差异",
    "tm_prev_inline": "上一处行内差异",
    "tm_toolbar": "工具栏",
    "tm_statusbar": "状态栏",
    "tm_linediffbar": "行差异条",
    "tm_locator": "定位条",
    "tm_wrap": "折行",
    "tm_moved": "移动块",
    "tm_inline": "行内差异",
    "tm_inline_word": "按词行内差异",
    "tm_cmp_ws": "比较空白",
    "tm_ign_ws": "忽略空白变化",
    "tm_ign_all_ws": "忽略全部空白变化",
    "tm_ignore_eol": "忽略换行符",
    "tm_show_ws": "显示空白",
    "tm_oneway": "单栏/双栏切换",
    "tm_switch": "左右视图对调",
    "tm_collapse": "折叠未改段",
    "tm_settings": "设置",
    "tm_filelist": "显示/隐藏补丁文件列表",
    "tm_help_topics": "帮助主题",
    "tm_about": "关于 TortoiseGitMerge...",
    "tm_help_text": "TortoiseGitMerge 文本比较 / 合并。",
    "tm_col": "列: 0",
    "tm_col_n": "列: {}",
    "tm_conflicts": "冲突",
    "tm_resolved": "已解决",
    "tm_no_result": "没有可保存的合并结果。",
    "tm_saved": "已写入 {}",
    "tm_saved_ok": "已保存。",
    "tm_save_which": "多个栏可写，保存哪一侧？",
    "tm_save_left": "保存左侧",
    "tm_save_right": "保存右侧",
    "tm_save_all": "全部保存",
    "tm_title_plain": "TortoiseGitMerge",
    "tm_has_conflicts": "文件仍有未解决冲突（约第 {} 行）。",
    "tm_save_anyway": "仍然保存",
    "tm_goto_conflict": "转到冲突处",
    "tm_mark_no_repo": "没有仓库路径，无法 git add。",
    "tm_mark_fail": "git add 失败，未能标记已解决。",
    "tm_mark_need_merge": "仅三路合并可将结果标记为已解决。",
    "tm_mark_ok": "已保存并 git add，冲突已标记解决。",
    "tm_ask_mark": "冲突已解决，是否 git add 标记该文件？",
    "tm_patch_none": "没有可导出的仓库文件。",
    "tm_open_two": "当前按左右两个文件比较。",
    "tm_file_tab": "文件",
    "tm_edit_tab": "编辑",
    "tm_group_edit": "编辑",
    "tm_group_nav": "导航",
    "tm_group_blocks": "块",
    "tm_group_ws": "空白",
    "tm_group_diff": "差异",
    "tm_group_view": "视图",
    "tm_view_bars": "栏",

    # ---- Log 对话框 ----
    "log_title": "日志",
    "log_graph": "图",
    "log_actions": "动作",
    "log_message": "信息",
    "log_author": "作者",
    "log_date": "日期",
    "log_hash": "SHA-1",
    "log_email": "电子邮件",
    "log_commit_name": "提交者",
    "log_commit_email": "提交者电子邮件",
    "log_commit_date": "提交日期",
    "log_file_path": "文件",
    "log_file_filename": "文件名",
    "log_file_ext": "扩展名",
    "log_file_status": "状态",
    "log_file_add": "增加",
    "log_file_del": "删除",
    "log_file_modified": "修改日期",
    "log_file_size": "大小",
    "log_file_from": "(来自 {})",
    "filediff_file": "文件",
    "filediff_ext": "扩展名",
    "filediff_action": "动作",
    "filediff_add": "增加",
    "filediff_del": "删除",
    "log_file_group": "已修改的文件",
    "status_group_unversioned": "未版本控制的文件",
    "status_group_ignored": "已忽略的文件",
    "status_group_localignore": "忽略本地更改的文件",
    "log_diff_parent": "与父提交 {} 的差异: {}",
    "log_st_modified": "已修改",
    "log_st_added": "已添加",
    "log_st_deleted": "已删除",
    "log_st_renamed": "已重命名",
    "log_st_copied": "已复制",
    "log_st_type": "类型变更",
    "log_st_unmerged": "未合并",
    "log_compare_wc": "与工作副本比较",
    "log_compare_prev": "与上一版本比较",
    "log_compare_base": "与基版本比较",
    "log_compare_two": "比较两个修订",
    "log_compare_changes": "比较两个提交的变更集",
    "log_gnudiff": "显示统一差异",
    "log_browse": "浏览版本库",
    "log_merge_to": "合并到「{}」",
    "log_reset": "重置「{}」到此…",
    "log_switch": "切换/签出…",
    "log_newbranch": "在此创建分支…",
    "log_newtag": "在此创建标签…",
    "log_export": "导出…",
    "log_revert": "还原此提交引入的更改",
    "log_cherry_pick": "Cherry Pick…",
    "log_create_patch": "创建补丁…",
    "log_copy_clip": "复制到剪贴板",
    "log_copyhash": "完整哈希",
    "log_copyshort": "短哈希",
    "log_copy_authors": "作者",
    "log_copy_emails": "电子邮件",
    "log_copy_subjects": "主题",
    "log_copy_messages": "完整信息",
    "log_copy_refs": "分支/标签",
    "log_show_branches": "显示此提交所在的引用",
    "log_find": "查找…",
    "log_show_log": "显示日志",
    "log_blame": "Blame",
    "log_revert_to_rev": "还原到此版本",
    "log_save_as": "另存为…",
    "log_view_rev": "查看修订",
    "log_open": "打开",
    "log_open_with": "打开方式…",
    "log_explore": "在资源管理器中打开",
    "log_copy_full": "完整路径",
    "log_copy_rel": "相对路径",
    "log_copy_name": "文件名",

    # ---- 仓库管理面板 (MainMenuDlg) ----
    "repo_manager_title": "仓库管理",
    "repo_manager_hint": "双击仓库切换；展开可查看子模块",
    "repo_menu_commit": "Commit…",
    "repo_menu_log": "Show log",
    "repo_menu_pull": "Pull…",
    "repo_menu_push": "Push…",
    "repo_menu_sync": "Sync",
    "repo_menu_revert": "Revert…",
    "repo_menu_cleanup": "Clean Up…",
    "repo_menu_remove": "从列表移除",
    "repo_menu_open_sub": "打开子模块",
    "browser_tab_repo": "仓库管理",
    "browser_tab_folder": "目录树",
    "folder_hint": "双击仓库目录打开；右键仓库目录可添加并执行操作",
    "menu_add_to_repo_list": "添加到仓库管理",
    "menu_left_panel": "左侧面板",
    "repo_menu_clone": "Git Clone…",
    "repo_menu_settings": "Settings",
    "menu_submodule": "子模块",
    "menu_submodule_hint": "双击子模块打开其窗口",
    "menu_open_content": "打&开",
    "menu_nav_back": "←",
    "menu_nav_back_tip": "后退",
    "menu_nav_forward": "→",
    "menu_nav_forward_tip": "前进",
    "menu_nav_up": "↑",
    "menu_nav_up_tip": "上一级",
    "menu_nav_refresh": "⟳",
    "menu_nav_refresh_tip": "刷新",
    "file_menu_open": "打开",
    "file_menu_show_in": "显示位置",
    "file_menu_diff": "Diff…",
    "file_menu_blame": "Blame…",
    "file_menu_log": "Show log",
    "file_menu_stash": "Stash changes…",
    "menu_commands": "命令(&C)",
    "menu_grp_changes": "本地更改",
    "menu_grp_inspect": "查看/比较",
    "menu_grp_syncing": "获取/发布",
    "menu_grp_branch": "分支/合并",
    "menu_grp_clone": "仓库",
    "menu_grp_format": "补丁/导出",
    "menu_grp_utils": "工具/其他",
    "menu_grp_other": "其他",
    "menu_cmd_commit": "Commit…",
    "menu_cmd_revert": "Revert…",
    "menu_cmd_cleanup": "Clean Up…",
    "menu_cmd_add": "Add…",
    "menu_cmd_remove": "Remove…",
    "menu_cmd_ignore": "Ignore…",
    "menu_cmd_unignore": "Unignore…",
    "menu_cmd_rename": "Rename…",
    "menu_cmd_log": "Show log",
    "menu_cmd_diff": "Diff",
    "menu_cmd_blame": "Blame…",
    "menu_cmd_sync": "Sync",
    "menu_cmd_pull": "Pull…",
    "menu_cmd_push": "Push…",
    "menu_cmd_fetch": "Fetch…",
    "menu_cmd_branch": "Branch…",
    "menu_cmd_merge": "Merge…",
    "menu_cmd_rebase": "Rebase…",
    "menu_cmd_switch": "Switch/Checkout…",
    "menu_cmd_bisect": "Bisect…",
    "menu_cmd_reset": "Reset…",
    "menu_cmd_stash": "Stash changes…",
    "menu_cmd_clone": "Clone…",
    "menu_cmd_submodule": "Submodule…",
    "menu_cmd_repocreate": "Create repository…",
    "menu_cmd_export": "Export…",
    "menu_cmd_formatpatch": "Format Patch…",
    "menu_cmd_importpatch": "Import Patch…",
    "menu_cmd_settings": "Settings",
    "menu_cmd_help": "Help",
    "menu_cmd_shell": "Shell…",
    "menu_cmd_reflog": "Reflog…",
    "menu_cmd_repostatus": "Repo Status",
    "menu_cmd_revisiongraph": "Revision Graph",
    "menu_cmd_repobrowser": "Repo Browser",
    "menu_cmd_showcompare": "Show Compare…",
    "menu_cmd_requestpull": "Request Pull…",
    "menu_cmd_sendmail": "Send Mail…",
    "menu_cmd_cat": "Cat…",
    "menu_cmd_clean": "Clean…",
    "menu_cmd_resolve": "Resolve…",
    "menu_cmd_merge3": "Merge Three-way…",
    "menu_cmd_worktreelist": "Worktrees…",
    "menu_cmd_newworktree": "New Worktree…",
    "menu_cmd_addremote": "Manage remotes…",
    "menu_cmd_lfslock": "Locks…",
    "menu_cmd_changed": "Changed…",
    "menu_cmd_revision": "Revision…",
    "menu_cmd_daemon": "Daemon…",
    "menu_cmd_rtfm": "Help / RTFM…",
    "menu_cmd_firststart": "First Start Wizard…",
    "menu_cmd_updatecheck": "Check for updates…",
    "menu_cmd_mergeabort": "Abort Merge…",
"menu_cmd_stashsave": "Stash save…",
    "menu_cmd_stashapply": "Stash Apply",
    "menu_cmd_stashpop": "Stash pop…",
    "menu_cmd_stashlist": "Stash list…",
    "menu_cmd_svnignore": "Import SVN Ignore ...",
    "menu_cmd_subsync": "Submodule sync…",
    "menu_cmd_prevdiff": "Diff with previous",
    "menu_cmd_review": "Review…",
    "menu_cmd_inaccessible": "Inaccessible",
    "menu_cmd_svndcommit": "SVN DCommit…",
    "menu_cmd_svnrebase": "SVN Rebase…",
    "menu_cmd_svnfetch": "SVN Fetch…",
    "menu_cmd_logsubmodule": "Show submodule log",
    "menu_cmd_browserefs": "Browse References…",
    "menu_cmd_bisectgood": "Bisect Good",
    "menu_cmd_bisectbad": "Bisect Bad",
    "menu_cmd_bisectskip": "Bisect Skip",
    "menu_cmd_bisectreset": "Bisect Reset",
    "menu_cmd_conflicteditor": "Conflict Editor…",
    "menu_cmd_removekeep": "Remove (keep local)…",
    "menu_cmd_tag": "Tag…",
    "menu_cmd_submoduleadd": "Add submodule…",
    "menu_cmd_submoduleupdate": "Submodule Update…",
    "menu_cmd_about": "About",
    "content_hint": "单击左侧目录/仓库查看子文件夹；双击进入或打开",
    # ---- 主界面（mainmenu）----
    "menu_title": "PyTortoiseGit 主窗口",
    "menu_file": "文件(&F)",
    "menu_open_repo": "打开仓库…",
    "menu_view": "视图(&V)",
    "menu_help": "帮助(&H)",
    "menu_path_label": "仓库路径:",
    "menu_running": "正在执行：{name}",
    "menu_not_repo": "不是 Git 仓库：{msg}",
    "menu_select_first": "请先选择仓库路径。",
    "menu_done": "完成：{name}",
    # ---- 日志对话框（logdlg）----
    "log_msg_hint": "提交信息…",
    "log_filter": "过滤…",
    "log_help": "搜索语法：author:xxx / grep:yyy，回车刷新。\n双击提交可与上一版本比较。",
    "log_commits": "个提交",
    # ---- 提交对话框（commitdlg）----
    "commit_hint": "第一行是标题，空行后是正文",
    "commit_amend": "修订上一次提交",
    "commit_amend_diff": "显示到上次提交的改动",
    "commit_set_date": "设置作者日期",
    "commit_reset_date": "重置",
    "commit_set_author": "设置作者",
    "commit_signoff": "添加 Signed-off-by",
    "commit_help": "第一行是标题，空一行后写正文。勾选左侧复选框来控制提交哪些文件。",
    "commit_cancel_confirm": "真的想取消吗？未提交的内容将丢失。",
    "commit_view_patch": "查看补丁",
    "commit_text_info": "{chars} 字符 / {lines} 行",
    "commit_nothing": "没有选中要提交的文件",
    "commit_empty_msg": "请填写提交信息",
    "commit_newname": "请输入新分支名",
    "commit_branch_exists": "分支 {name} 已存在",
    "commit_failed": "提交失败",
    "menu_open": "在编辑器打开",
    "menu_copy_path": "复制路径",
    "menu_diff_file": "查看 diff",
    "menu_blame": "在此文件上运行 Blame",
    # ---- 变更列表（changedlg）----
    "changes_stash_failed": "暂存失败",
    "changes_unstage": "取消暂存",
    "changes_stage": "加入暂存",
    "changes_diff_head": "与 HEAD 比较",
    "changes_revert": "撤消更改…",
    "changes_save_unified": "显示该文件补丁",
    "changes_revert_q": "撤销对 {path} 的修改？",
    # ---- 同步（sync）----
    "sync_title": "同步",
    "sync_in": "待拉取",
    "sync_out": "待推送",
    "sync_help": "选择本地/远程分支与远程 URL，执行拉取或推送。",
    "sync_no_remote": "没有配置远端",
    "sync_ab": "{branch}: 领先 {ahead}，落后 {behind}",
    "sync_in_sync": "与远程一致",
    "sync_remote_list": "远端列表：\n",
    "sync_failed": "同步失败",
    # ---- 差异对话框（diffdlg）----
    "diff_summary": "{files} 个文件，+{lines} 行改动",
    "diff_working_tree": "工作区",
    # ---- 文件状态（git/status）----
    "status_untracked": "未跟踪",
    "status_modified": "已修改",
    "status_added": "已暂存",
    "status_deleted": "已删除",
    "status_renamed": "已重命名",
    "status_copied": "已复制",
    "status_unmerged": "未合并",
    "status_typechange": "类型变化",
    "status_ignored": "被忽略",
    # ---- 子模块状态（git/submodule）----
    "submodule_ok": "正常",
    "submodule_notinit": "未初始化",
    "submodule_mismatch": "提交不一致",
    "submodule_conflict": "冲突",
    # ---- 引用浏览（browserefs）----
    "browse_refs": "分支与标签",
    "browse_current": "当前分支",
    "ref_name": "名称",
    "ref_target": "指向",
    "ref_subject": "信息",
    "browse_checkout": "检出",
    "browse_delete": "删除…",
    "browse_branches": "分支",
    "browse_remotes": "远程分支",
    "browse_tags": "标签",
    "browse_checkout_remote": "无法直接检出远程分支 {name}，请用 git checkout -b <local> {name}",
    # ---- 首次启动向导（firststartdlg）----
    "firststart_title": "欢迎使用 PyTortoiseGit",
    "firststart_hint": "此向导引导你完成基础 Git 配置：\n1. 选择界面语言\n2. 定位 git.exe\n3. 填写姓名/邮箱\n4. 选择 SSH 客户端\n",
    "firststart_language": "界面语言",
    "firststart_lang_hint": "选择界面语言。",
    "firststart_git": "Git 可执行文件",
    "firststart_git_hint": "TortoiseGit 需要一个 git.exe。",
    "firststart_user": "用户信息",
    "firststart_auth": "身份验证",
    "firststart_ssh_hint": "选择 SSH 客户端。",
    # ---- 设置（settingsdlg）----
    "settings_title": "设置",
    # ---- Blame（blamedlg）----
    "menu_show_log": "查看该提交的日志",
    # ---- Reflog（reflogdlg）----
    "reflog_title": "引用日志 (reflog)",
    "reflog_selector": "选择器",
    "log_revision": "修订",
    "reflog_hint": "当前分支的 reflog",
    "log_checkout": "检出此提交…",
    "log_diff": "与此提交比较…",
    # ---- 创建分支/标签（createbranchdlg）----
    "branch_new": "新建分支",
    "branch_name": "分支名称",
    "branch_switch": "创建后立即切到该分支",
    "branch_track": "基于当前分支",
    "tag_new": "新建标签",
    "tag_name": "标签名称",
    "tag_msg_hint": "仅附注标签需要",
    "tag_message": "附注",
    "tag_annotated": "创建附注标签",
    # ---- 右键菜单集成（shelldlg）----
    "shell_title": "右键菜单集成",
    "shell_install": "安装右键菜单",
    "shell_uninstall": "卸载右键菜单",
    "shell_already": "右键菜单已安装。",
    "shell_not_installed": "右键菜单未安装。",
    # ---- 检查更新（checkforupdatesdlg）----
    "upd_file": "文件",
    "upd_size": "大小",
    "upd_source": "检查来源：PyTortoiseGit 仓库",
    "upd_latest": "最新",
    "upd_result": "您已使用最新版本。",
    "upd_no_downloads": "无可用下载",
    "upd_changelog": "PyTortoiseGit 无远端更新服务器。\n功能更新请关注仓库发布。",
    # ---- 克隆（clonedlg）----
    "clone_title": "克隆仓库",
    "clone_help": "填入要克隆的仓库 URL 与目标目录，开始克隆。",
    "clone_dir": "目录",
    "clone_putty": "选择 Putty 密钥",
    "clone_not_empty": "目标目录非空，仍要继续吗？",
    "clone_failed": "克隆失败",
    # ---- 杂项 ----
    "none": "（无）",
    "blame_col_line": "行",
    "blame_col_commit": "提交",
    "blame_col_author": "作者",
    "blame_col_date": "日期",
    "blame_col_code": "代码",
    "blame_error": "错误",
    "blame_lines": "行",
    "browse_delete_confirm": "确定删除「{name}」吗？",
    "shell_installed": "已写入 {n} 个右键菜单项（重新打开资源管理器后生效）。",
    "shell_uninstalled": "已删除 {n} 个右键菜单项。",
    "help": "帮助(&H)",
    # ---- 首次启动向导补充 ----
    "firststart_lang": "语言(&L)：",
    "firststart_check": "立即检查(&H)",
    "firststart_name": "姓名(&N)：",
    "firststart_dontsave": "现在不保存这些设置(&D)。",
    "firststart_ssh": "SSH（URL 形如 \"git@example.com\"）",
    "firststart_genkey": "生成 PuTTY 密钥对(&G)",
    "firststart_adv": "高级(&A)...",
    # ---- Reflog 补充 ----
    "reflog_search": "搜索(&S)...",
    "reflog_clearstash": "清除暂存(&C)",
    # ---- 检查更新补充 ----
    "upd_download": "下载(&D)",
    "upd_close": "关闭(&C)",
    "upd_your": "你的版本：{}",
    "upd_current": "当前版本：{}",
    # ---- 克隆补充 ----
    "clone_group": "克隆现有仓库",
    "clone_svn_group": "从 SVN 仓库",
    "clone_url": "URL：",
    "clone_browse_url": "浏览(&B)...",
    "clone_browse_dir": "浏览(&W)...",
    "clone_depth": "深度",
    "clone_recursive": "递归",
    "clone_bare": "克隆为裸仓库",
    "clone_nocheckout": "不检出",
    "clone_branch": "分支",
    "clone_origin": "远程名称",
    "clone_svn": "从 SVN 仓库(&S)",
    "clone_svn_trunk": "主干(&T)：",
    "clone_svn_tag": "标签(&G)：",
    "clone_svn_branch": "分支(&H)：",
    "clone_svn_from": "来自(&F)：",
    "clone_username": "用户名(&N)：",
    # ---- 冲突/解决 ----
    "conflicts_take_ours": "取我方 (ours)",
    "conflicts_take_theirs": "取对方 (theirs)",
    "conflicts_mark": "标记已解决",
    "conflicts_extmerge": "合并工具解决",
    "resolve_edit": "解决/标记已解决",
    "resolve_merge": "用合并工具解决",
    "resolve_diff": "查看冲突",
    # ---- 应用补丁 ----
    "apply_patch_file": "Patch 文件",
    "apply_add": "选择补丁",
    # ---- 关于 ----
    "about_contrib": "Significant contributions by (Git 仓库):",
    # ---- 提交引用/引用名 ----
    "commitref_ref": "引用",
    "menu_copy_ref": "复制引用名",
    "menu_copy_tag": "复制标签名",
    # ---- 自动文本测试 ----
    "autotext_match": "匹配：{}",
    "autotext_nomatch": "无匹配",
    # ---- 格式补丁 ----
    "fmt_patch_dir": "输出目录",
    "fmt_patch_unified": "保存 unified diff",
    # ---- 修订图 ----
    "revgraph_graph": "图 / 提交",
    "revgraph_stats": "统计",
    # ---- 导出/推送/重命名/工具关联/工作树 ----
    "export_file": "Zip 文件",
    "push_ready": "就绪",
    "rename_browse": "选择文件",
    "tool_browse": "选择工具",
    "wt_dir": "工作树目录",
    # ---- 补充 ----
    "patches": "个补丁",
    "about_authors": "PyTortoiseGit contributors\n基于 TortoiseGit (GPLv2, tortoisegit.org)\n图标经 TortoiseSVN (tortoisesvn.net) 授权使用",
    "about_reimpl": "基于 TortoiseGit 复刻",
    "about_icons": "图标源自 TortoiseSVN（tortoisesvn.net）",
    "logorder_topo": "按拓扑顺序",
    "logorder_date": "按日期",
    "logorder_author_date": "按作者日期",
    "logorder_default": "默认",
    "choose_folder": "选择文件夹",
    # ---- 命令消息 ----
    "help_title": "帮助",
    "help_text": "用法：app.py /command:&lt;名称&gt; [/path:&lt;路径&gt;]\n\n可用命令：\n{cmds}",
    "inaccessible_title": "路径不可访问",
    "inaccessible_text": "路径不可访问：{}",
    "icon_title": "图标缓存",
    "icon_text": "图标缓存已清除（需重启资源管理器生效）。",
    "ctx_title": "右键菜单",
    "ctx_installed": "Win11 右键菜单已安装。",
    "remove_title": "移除",
    "remove_confirm": "从 git 移除选中的文件？",
    "rtfm_title": "文档",
    "rtfm_text": "打开文档：{}",
    "crash_text": "crash 调试命令：已捕获为信息框（未真正崩溃）。",
    "stash_list": "Stash 列表",
    "unignore_done": "已取消忽略（更新 .gitignore）",
    # ---- Shell 集成 ----
    "shell_commit": "提交 (PyTortoiseGit)",
    "shell_log": "日志 (PyTortoiseGit)",
    "shell_changed": "检查修改 (PyTortoiseGit)",
    "shell_sync": "同步 (PyTortoiseGit)",
    "shell_browse": "分支与标签 (PyTortoiseGit)",
    "shell_settings": "设置 (PyTortoiseGit)",
    "shell_blame": "标注此文件 (Blame)",
    "shell_diff": "与 HEAD 比较…",
    "shell_windows_only": "Shell 集成仅支持 Windows。",
    "shell_state_installed": "已安装",
    "shell_state_not_installed": "未安装",
    "shell_status": "右键菜单状态：{mode}\n可执行：{py}\n入口：{app}\n\n安装到 文件 / 文件夹 / 文件夹空白处 三类右键菜单。修改注册表后，通常需要重新打开资源管理器才生效。",
    # ---- 命令行 ----
    "cli_usage": "用法：app.py /command:<name> [/path:<path>] [/msg:<message>] ...",
    "cli_commands": "可用命令：about  clone  commit  diff  log  blame  browse  reflog",
    "cli_examples": "例：",
    # ---- Git 错误/状态 ----
    "merge_in_progress": "仓库处于 {state} 状态，请先完成或中止该操作",
    "state_merge": "合并",
    "state_rebase": "变基",
    "not_a_repository": "不是 git 仓库：{path}",
    "no_commits": "(无提交)",
    "exit_code": "退出码",
    "git_not_found": "找不到 git 可执行文件，请安装 git 或设置 GIT_PATH 环境变量",
    "command_timeout": "命令执行超时",
    "error": "错误",
    "unhandled_exception": "{label}发生未捕获异常：\n{exc}\n\n详情已写入日志文件。",
    "thread": "线程",
    "invalid_filename": "无效的文件名：{name}",
    # ---- TortoiseMerge 设置 ----
    "tabmode_tab": "使用制表符",
    "tabmode_spaces": "使用空格",
    "tabmode_smart": "智能制表",
    "settings_backup": "合并时备份文件",
    "settings_firstdiff": "加载后跳到首个差异",
    "settings_firstconflict": "加载后跳到首个冲突",
    "settings_ignorews": "忽略空白差异",
    "settings_ignoreeol": "忽略换行符差异",
    "settings_ignorecase": "忽略大小写",
    "settings_onepane": "单栏视图",
    "settings_linenumbers": "显示行号",
    "settings_utf8": "默认以 UTF-8 保存",
    "settings_autoadd": "自动添加新文件",
    "settings_editorconfig": "启用 EditorConfig",
    "settings_font": "字体:",
    "settings_fontsize": "字号:",
    "settings_tabmode": "制表模式:",
    "settings_tabsize": "制表宽度:",
    "settings_context": "上下文行数:",
    "settings_maxinline": "最大行内差异长度:",
    "color_pick": "选择颜色",
    "merge_settings_title": "TortoiseMerge 设置",
    "merge_settings_main": "常规",
    "merge_settings_colors": "颜色",
    # ---- TortoiseMerge 查找 ----
    "find_title": "查找/替换",
    "find_label": "查找内容:",
    "replace_label": "替换为:",
    "find_case": "区分大小写",
    "find_limit": "仅在修改的行中查找",
    "find_up": "向上搜索",
    "find_whole": "全词匹配",
    "find_find": "查找",
    "find_replace": "替换",
    "find_replace_all": "全部替换",
    "find_count": "计数",
    # ---- TortoiseMerge 打开 ----
    "open_path_hint": "选择文件…",
    "open_title": "选择目录",
    "open_base": "基础文件(base):",
    "open_their": "对方文件(their):",
    "open_your": "我方文件(your):",
    "open_diff": "统一 diff 文件:",
    "open_patchdir": "补丁目录:",
    "open_from_clipboard": "从剪贴板获取补丁",
    # ---- TortoiseMerge 补丁文件 ----
    "filepatches_title": "补丁文件",
    "filepatches_path": "文件",
    "filepatches_content": "内容",
    "filepatches_version": "版本",
    "filepatches_patchall": "全部应用",
    "filepatches_patchsel": "应用选中",
    # ---- TortoiseMerge 编码/正则/跳转 ----
    "encoding_title": "编码 / 行尾",
    "encoding_label": "编码:",
    "eol_label": "行尾:",
    "regex_filter_title": "正则过滤",
    "regex_name": "名称",
    "regex_expr": "正则表达式",
    "regex_replace": "替换为",
    "regex_filters_title": "正则过滤列表",
    "gotoline_title": "跳转到行",
    "gotoline_label": "行号:",
    # ---- TortoiseMerge 颜色状态/行尾 ----
    "color_state_removed": "删除行",
    "color_state_added": "新增行",
    "color_state_edited": "修改行",
    "color_state_conflict": "冲突行",
    "eol_auto": "自动",
    "eol_none": "无",
    "merge_about_version": "版本 {ver} · 基于 TortoiseGit 复刻",
    "filetextlines_not_file": "不是文件: {path}",
    "filetextlines_binary": "二进制文件: {path}",
    "patch_no_diff": "没有解析到补丁",
    # ---- 命令补充 ----
    "merge3_need_path": "需要 /path:<文件>",
    "not_set": "(未设置)",
    "sync_fetch": "抓取",
    "sync_pull": "拉取",
    "sync_push": "推送",
    "no_path_provided": "(未提供 /path)",
    "cleanup_title": "仓库清理",
    "crash_title": "崩溃",
    "daemon_title": "Git 守护进程",
    "pgpfp_title": "GPG 指纹",
    "pgpfp_text": "签名密钥：{}",
    "about_versionbox": "版本信息",
    "about_check_updates": "检查更新...",
    "add_col_path": "路径",
    "add_selectall": "全选/取消全选(&A)",
    "add_ignored": "包含已忽略文件(&I)",
    "addremote_name": "名称：",
    "apply_up": "上移(&U)",
    "apply_down": "下移(&D)",
    "apply_remove": "移除(&R)",
    "apply_3way": "三方合并(&3)",
    "apply_ignore_space": "忽略空白变化(&I)",
    "apply_sign_off": "添加 ",
    "apply_keep_cr": "保留 CR(&K)",
    "apply_tab_patches": "补丁",
    "apply_apply": "应用(&P)",
    "apply_cancel": "取消(&C)",
    "autotext_hint": "输入要测试的文件内容：",
    "autotext_scan": "扫描",
    "autotext_exit": "退出",
    "bisect_good": "最后已知良好(&G)：",
    "bisect_bad": "首个已知错误(&B)：",
    "cat_title": "Cat - {}",
    "rc_col_path": "路径",
    "rc_col_ext": "扩展名",
    "rc_col_status": "状态",
    "rc_col_add": "新增行",
    "rc_col_del": "删除行",
    "rc_col_moddate": "修改日期",
    "changes_stash": "暂存",
    "commit_perform": "提交",
    "changes_stats": "行: {add}(+) {remove}(-) 文件: 普通={normal}, 未版本控制={unver}, ",
    "changes_stash_save": "暂存更改",
    "changes_stash_list": "暂存列表",
    "changes_stash_pop": "暂存弹出",
    "changes_stash_apply": "应用暂存",
    "clean_all": "移除所有未跟踪文件(&A) (-fx)",
    "clean_no": "移除非忽略的未跟踪文件(&N) (-f)",
    "clean_ignored": "移除已忽略文件 (-fX)",
    "clean_dir": "移除未跟踪目录(&D) (-d)",
    "clean_unmanaged": "移除含 .git 目录的未管理目录",
    "clean_recycle": "不使用回收站",
    "clean_dry": "试运行",
    "clean_sub": "子模块",
    "clean_note": "注意：此命令影响整个工作树。",
    "commit_msg_group": "信息(&M)：",
    "commit_list_group": "已做的更改 (F5: 刷新，双击文件查看 ",
    "commit_to_label": "提交到：",
    "commit_newbranch": "新分支",
    "commit_bugid_label": "Bug-ID/Issue-Nr:",
    "commit_check_label": "检查：",
    "commit_staging": "暂存支持（实验性）",
    "commit_show_unversioned": "显示未版本控制文件(&U)",
    "commit_partial_staging": "部分暂存>>",
    "commit_partial_unstaging": "部分取消暂存>>",
    "commit_no_autoselect": "不自动选择子模块",
    "commit_whole_project": "显示整个项目(&W)",
    "commit_message_only": "仅信息(&Y)",
    "commit": "提交(&O)",
    "commit_push": "提交并推送(&P)",
    "commit_stats": "已选 {sel} 个文件，共 {total} 个文件",
    "showlog": "显示日志",
    "commitref_filter": "过滤: ",
    "conflicteditor_title": "冲突 - {}",
    "conflicteditor_reminder": "删除/修改合并冲突",
    "conflicteditor_local": "本地:",
    "conflicteditor_diff": "显示更改(&C)",
    "conflicteditor_remote": "远程:",
    "conflicteditor_delete": "删除",
    "conflicteditor_abort": "中止",
    "changelist_hint": "输入变更列表名称：",
    "init_bare": "创建为裸仓库（无工作目录）",
    "init_desc": "如果你打算在此文件夹内工作，",
    "auth_title": "身份验证",
    "auth_user": "用户名(&U)：",
    "auth_save": "保存身份验证(&S)",
    "auth_reqs": "请求用户名和密码",
    "auth_passwd": "密码",
    "auth_passwd_label": "密码(&P)：",
    "certcheck_title": "TortoiseGit",
    "certcheck_desc": "证书验证失败！",
    "certcheck_open": "打开证书",
    "certcheck_accept": "接受证书",
    "deletetag_remote": "远程：",
    "deletetag_tag": "标签",
    "deletetag_selectall": "全选/取消全选(&A)",
    "deletetag_delete": "删除(&D)",
    "deletetag_close": "关闭",
    "export_head": "HEAD(&H)",
    "export_branch": "分支(&B)",
    "export_tag": "标签(&T)",
    "export_commit": "提交(&C)",
    "export_whole": "整个项目(&W)",
    "fmt_patch_since": "起始",
    "fmt_patch_num": "提交数量",
    "fmt_patch_range": "范围",
    "fmt_patch_mail": "创建后发送邮件",
    "fmt_patch_noprefix": "不使用 a/ 和 b/ 前缀",
    "switch_branch": "分支(&B)",
    "switch_tag": "标签(&T)",
    "switch_commit": "提交(&C)",
    "switch_newbranch": "创建新分支(&N)",
    "switch_force": "覆盖工作树更改(&F)",
    "switch_merge": "合并(&M)",
    "switch_track": "跟踪(&R)",
    "switch_override": "覆盖已存在的分支(&O)",
    "ignore_onlyfolder": "仅在所在文件夹忽略",
    "ignore_recursive": "递归忽略",
    "ignore_root": "仓库根目录的 .gitignore",
    "ignore_local": "所在目录中的 .gitignore",
    "ignore_exclude": ".git/info/exclude",
    "url_label": "URL(&U)：",
    "input_hint": "输入日志信息(&M)：",
    "lfs_path": "路径",
    "lfs_owner": "所有者",
    "lfs_selectall": "全选/取消全选(&A)",
    "lfs_force": "强制(&F)",
    "lfs_unlock": "解锁(&U)",
    "log_branch_label": "分支：",
    "log_from": "从：",
    "log_to": "到：",
    "log_whole": "显示整个项目(&W)",
    "log_allbranch": "所有分支(&A)",
    "log_stats": "统计(&T)",
    "log_walk": "遍历行为(&H)",
    "log_view": "视图(&V)",
    "logorder_label": "提交排序：",
    "mergeabort_reminder": "为中止合并进度，将执行一次重置（类型）！",
    "mergeabort_merge": "合并(&M)：重置索引并尝试重建合并前状态",
    "mergeabort_mixed": "混合(&M)：保持工作树不变，重置索引",
    "mergeabort_hard": "硬(&H)：重置工作树和索引（丢弃更改）",
    "mergeabort_show": "显示工作树中修改的文件(&W)",
    "patch_view": "查看补丁",
    "pullfetch_title": "拉取/抓取",
    "pull_remote": "远程(&R)：",
    "pull_url": "任意 URL(&U)：",
    "pull_branch": "远程分支(&B)：",
    "pull_squash": "压缩(&S)",
    "pull_noff": "不使用快进",
    "pull_nocommit": "不提交(&M)",
    "pull_depth": "深度",
    "pull_ffonly": "仅快进(&O)",
    "pull_tags": "标签",
    "pull_prune": "清理",
    "pull_putty": "自动加载 PuTTY 密钥(&K)",
    "pull_manage": "管理远程",
    "pull_rebase": "抓取后启动变基(&L)",
    "fetch_title": "抓取",
    "push_ref_group": "引用",
    "push_dest_group": "目标",
    "push_opt_group": "选项",
    "push_all": "推送所有分支(&P)",
    "push_local": "本地(&L)：",
    "push_remote": "远程(&R)：",
    "push_rd_remote": "远程(&M)：",
    "push_manage": "管理(&G)",
    "push_rd_url": "任意 URL(&U)：",
    "push_force_lease": "带租约强制(&W)",
    "push_force": "强制(&F)",
    "push_tags": "包含标签(&T)",
    "push_putty": "自动加载 PuTTY 密钥(&A)",
    "push_upstream": "设置上游/跟踪远程分支(&S)",
    "push_push_remote": "始终推送到选定的远程存档",
    "push_push_branch": "始终推送到选定的远程分支",
    "push_sub": "递归子模块",
    "push_option": "推送选项(&O)：",
    "rename_name": "新名称(&N)：",
    "repobrowser_path": "路径：",
    "repobrowser_rev": "修订：",
    "repobrowser_tree": "路径",
    "repobrowser_name": "名称",
    "repobrowser_mode": "模式",
    "repobrowser_size": "大小",
    "req_start": "开始(&S)",
    "req_url": "仓库 URL(&U)",
    "req_end": "结束",
    "req_mail": "创建后发送邮件",
    "reset_branch": "分支(&B)",
    "reset_tag": "标签(&T)",
    "reset_commit": "提交(&C)",
    "reset_soft": "软(&S)：保持工作树和索引不变",
    "reset_mixed": "混合(&M)：保持工作树不变，重置索引",
    "reset_hard": "硬(&H)：重置工作树和索引（丢弃更改）",
    "reset_showmod": "显示工作树中修改的文件(&W)",
    "reset_cur": "当前分支：",
    "resolve_path": "路径",
    "resolve_status": "状态",
    "resolve_selectall": "全选/取消全选(&A)",
    "resolve_reminder": "提醒：解决后提交你的更改",
    "revert_col_path": "路径",
    "revert_col_status": "状态",
    "revert_selectall": "全选/取消全选(&A)",
    "revert_unver": "注意：文件夹包含未版本控制的项目",
    "revf_hint": "仅包含以下修订范围：",
    "revf_current": "仅当前分支",
    "revf_local": "仅本地分支",
    "revf_ok": "确定(&O)",
    "revf_reset": "重置过滤(&R)",
    "revgraph_title": "修订图",
    "sel_remote": "远程：",
    "mail_to": "收件人：",
    "mail_attach": "补丁作为附件",
    "mail_combine": "合并为一封邮件",
    "mail_setup": "邮件设置",
    "mail_send": "发送",
    "stat_type": "图表类型：",
    "stat_numweeks": "周数：",
    "stat_numauthor": "作者数：",
    "stat_numcommits": "分析的提交总数：",
    "stat_numfiles": "文件更改总数：",
    "stat_calc": "计算",
    "sync_local": "本地分支(&L)：",
    "sync_remote": "远程分支(&R)：",
    "sync_url": "远程 URL(&U)：",
    "sync_manage": "管理",
    "sync_putty": "自动加载 PuTTY 密钥(&K)",
    "sync_force": "强制(&F)",
    "sync_incoming": "待拉取",
    "sync_outgoing": "待推送",
    "sync_pull_rebase": "拉取并变基",
    "sync_push_upstream": "推送并设置上游",
    "sync_push_tags": "推送标签",
    "sync_push_all": "推送所有分支",
    "sync_submodule": "子模块",
    "sync_stash": "暂存",
    "sync_apply": "应用补丁(&A)",
    "sync_email": "邮件补丁(&E)",
    "sync_log": "显示日志(&L)",
    "sync_commit": "提交(&C)",
    "sync_manage_remote": "管理远程",
    "tool_ext": "扩展名：",
    "wt_browse": "浏览(&W)...",
    "wt_head": "HEAD",
    "wt_branch": "分支",
    "wt_tag": "标签(&T)",
    "wt_commit": "提交(&C)",
    "wt_newbranch": "创建新分支(&N)",
    "wt_checkout": "检出(&C)",
    "wt_force": "强制(&F)",
    "wt_detach": "分离(&D)",
    "wt_path": "路径",
    "wt_add": "添加(&A)",
    "wt_prune": "清理(&P)",
    "merge_about_title": "TortoiseMerge (PyTortoiseGit)",
    "call_add": "添加(&A)…",
    "call_edit": "编辑(&E)…",
    "call_remove": "移除(&R)",
    "log": "日志",
    "stat_graph": "图表",
}


def tr(key: str, default: str | None = None) -> str:
    """取界面文案。

    约定：`default` 为**英文**文案，`STRINGS` 为**中文**文案。
      * 英文界面：返回 default（英文），缺失时回退 STRINGS。
      * 中文界面：返回 STRINGS（中文），缺失时回退 default。
    """
    if _translator is not None:
        translated = _translator(key)
        if translated:
            return translated
    if _current_lang == "en":
        return default or STRINGS.get(key) or key
    return STRINGS.get(key, default or key)


def set_language(lang: str) -> None:
    """切换界面语言："zh"（中文）/ "en"（英文）；其余回退中文。"""
    global _current_lang
    v = str(lang or "").lower()
    _current_lang = "zh" if v.startswith("zh") else ("en" if v.startswith(("en", "de")) else "zh")


def get_language() -> str:
    return _current_lang


def set_translator(func: Optional[Callable[[str], str]]) -> None:
    """安装自定义翻译函数（例如接入 Qt QTranslator 后）。"""
    global _translator
    _translator = func


def format_string(text: str, **kwargs) -> str:
    """格式化字符串表项（未提供参数时保留原占位符）。"""
    try:
        return text.format(**kwargs)
    except (KeyError, IndexError):
        return text